BATCH_SIZE = 64
IMAGE_SIZE = 64
NUM_CHANNELS = 1

NUM_EXT_FEATURES_CNN = 1
NUM_LABEL_BYTES = 16

GOP_LENGTH = 4

VECTOR_LENGTH_LIST = [64, 128, 256]

VECTOR_LENGTH = sum(VECTOR_LENGTH_LIST)

LSTM_DEPTH = 1
LSTM_MAX_LENGTH = 20
LSTM_OVERLAP_STRIDE = 10
LSTM_READ_LENGTH = LSTM_MAX_LENGTH
LSTM_OUTPUT_LENGTH = LSTM_MAX_LENGTH

NUM_EXT_FEATURES = LSTM_MAX_LENGTH * 2 + 1
